"""fnmusic-ext 管理 WebUI（fnmusic-sources 容器内第四个 supervisor 进程）。

定位：同容器内经 127.0.0.1 访问三源服务，subprocess 调 supervisorctl 切换音源
进程，直接读写挂载在 /repo 的仓库目录下的 .env（proxy 靠热重载生效）。
不挂 docker.sock、不做容器级操作。管理接口只接受飞牛网关注入的管理员身份。

前端为原生单页（static/，无构建、无 CDN 资产）。
"""
from __future__ import annotations

import asyncio
import io
import json
import logging
import os
import re
import shlex
import subprocess
import sys
import time
from contextlib import asynccontextmanager
from pathlib import Path

import httpx
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import FileResponse, JSONResponse, Response
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))  # /repo：复用 proxy/env_merge
from proxy.env_merge import (  # noqa: E402
    parse_env_file,
    preserve_user_comments,
    render_env,
    write_env_atomic,
)

logger = logging.getLogger("webui_service")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")

SERVICE_VERSION = "2.0.0"

CONF = {
    "repo_dir": os.environ.get("WEBUI_REPO_DIR", "/repo"),
    "musicdl_url": os.environ.get("WEBUI_MUSICDL_URL", "http://127.0.0.1:8001"),
    "musicbox_url": os.environ.get("WEBUI_MUSICBOX_URL", "http://127.0.0.1:8002"),
    "lx_url": os.environ.get("WEBUI_LX_URL", "http://127.0.0.1:8003"),
    "supervisorctl": os.environ.get("WEBUI_SUPERVISORCTL", "supervisorctl"),
    "env_header": "generated by install.sh — do not commit",
}

ENV_PATH = Path(CONF["repo_dir"]) / ".env"
VERSION_PATH = Path(CONF["repo_dir"]) / "VERSION"
STATIC_DIR = Path(__file__).resolve().parent / "static"

# 音源进程 ↔ 启用开关（三选一互斥）
PROVIDERS = {
    "musicdl": "FNMUSIC_MUSICDL_ENABLED",
    "musicbox": "FNMUSIC_NETEASE_ENABLED",
    "lxmusic": "FNMUSIC_LX_ENABLED",
}

# WebUI 可管理的配置键与元数据（kind/default/reload 驱动前端渲染与校验）。
# reload: hot=proxy 热重载即生效；process=需要切换/重启对应音源进程。
SCHEMA: dict[str, dict] = {
    "FNMUSIC_MUSICDL_ENABLED": {"kind": "bool", "default": "false", "group": "provider", "reload": "process", "label": "musicdl 聚合音源"},
    "FNMUSIC_NETEASE_ENABLED": {"kind": "bool", "default": "false", "group": "provider", "reload": "process", "label": "网易云音乐盒子"},
    "FNMUSIC_LX_ENABLED": {"kind": "bool", "default": "false", "group": "provider", "reload": "process", "label": "洛雪自定义源"},
    "FNMUSIC_ONLINE_SOURCES": {"kind": "csv", "default": "", "group": "musicdl", "reload": "process", "label": "musicdl 启用平台"},
    "MUSICDL_SOURCES": {"kind": "csv", "default": "", "group": "musicdl", "reload": "process", "label": "musicdl 服务白名单（联动）"},
    "LX_SOURCE_URL": {"kind": "str", "default": "", "group": "lx", "reload": "process", "label": "洛雪源脚本地址（http(s) URL 或 file:// 上传地址）"},
    "LX_SOURCE_LIST": {"kind": "str", "default": "[]", "group": "lx", "reload": "hot", "label": "洛雪源列表（JSON 数组）"},
    "LX_SOURCES": {"kind": "csv", "default": "kg,wy,mg,kw", "group": "lx", "reload": "hot", "label": "lx 平台（按源声明推导）"},
    "FNMUSIC_QUALITY_MODE": {"kind": "enum", "values": ["high", "balanced", "smooth"], "default": "high", "group": "quality", "reload": "hot", "label": "音质偏好"},
    "FNMUSIC_DL_QUALITY": {"kind": "enum", "values": ["app", "original", "standard"], "default": "app", "group": "quality", "reload": "hot", "label": "下载音质"},
    "FNMUSIC_RECOMMEND_HOT": {"kind": "bool", "default": "true", "group": "recommend", "reload": "hot", "label": "热门榜单推荐"},
    "FNMUSIC_RECOMMEND_DAILY": {"kind": "bool", "default": "true", "group": "recommend", "reload": "hot", "label": "每日推荐"},
    "FNMUSIC_TEE_SAVE_ENABLED": {"kind": "bool", "default": "true", "group": "tee", "reload": "hot", "label": "边听边存"},
    "FNMUSIC_TEE_SAVE_DIR": {"kind": "dir", "default": "", "group": "storage", "reload": "hot", "label": "下载目录（留空自动探测共享曲库）"},
    "FNMUSIC_CACHE_DIR": {"kind": "dir", "default": "", "group": "storage", "reload": "hot", "label": "歌曲缓存目录（留空=安装目录 cache）"},
    "FNMUSIC_TEE_CACHE_MAX": {"kind": "int", "default": "2", "min": 1, "max": 100, "group": "tee", "reload": "hot", "label": "关闭时滚动缓存数"},
    "FNMUSIC_FAV_AUTO_BIND": {"kind": "bool", "default": "false", "group": "tee", "reload": "hot", "label": "收藏自动绑定本地"},
    "FNMUSIC_AUTO_COVER": {"kind": "bool", "default": "true", "group": "tee", "reload": "hot", "label": "自动下载封面"},
    "FNMUSIC_LYRIC_AUTO_DL": {"kind": "bool", "default": "false", "group": "tee", "reload": "hot", "label": "自动下载歌词"},
    "FNMUSIC_OFFICIAL_BIND_TIMEOUT_S": {"kind": "int", "default": "120", "min": 10, "max": 3600, "group": "tee", "reload": "hot", "label": "官方绑定等待（秒）"},
    "FNMUSIC_TEE_HANDOFF_MAX": {"kind": "int", "default": "3", "min": 0, "max": 20, "group": "tee", "reload": "hot", "label": "切歌续传并行数"},
    "FNMUSIC_LIBRARY_SCAN_PATH": {"kind": "str", "default": "", "group": "tee", "reload": "hot", "label": "曲库重扫接口（选填）"},
    "FNMUSIC_LLM_BASE_URL": {"kind": "str", "default": "", "group": "llm", "reload": "hot", "label": "OpenAI 兼容 Base URL"},
    "FNMUSIC_LLM_API_KEY": {"kind": "secret", "default": "", "group": "llm", "reload": "hot", "label": "API Key"},
    "FNMUSIC_LLM_MODEL": {"kind": "str", "default": "gpt-4o-mini", "group": "llm", "reload": "hot", "label": "模型"},
    "FNMUSIC_SEARCH_TIMEOUT": {"kind": "int", "default": "15", "min": 1, "max": 60, "group": "search", "reload": "hot", "label": "搜索超时时间"},
    "FNMUSIC_SEARCH_PROBE": {"kind": "bool", "default": "false", "group": "search", "reload": "hot", "label": "逐曲探活(beta)"},
    "FNMUSIC_SEARCH_DEEP_PAGE": {"kind": "bool", "default": "true", "group": "search", "reload": "hot", "label": "搜索深分页"},
    "FNMUSIC_SEARCH_DEEP_MAX_PAGES": {"kind": "int", "default": "10", "min": 1, "max": 50, "group": "search", "reload": "hot", "label": "深分页页数上限"},
    "FNMUSIC_NETEASE_MY_PLAYLISTS": {"kind": "bool", "default": "false", "group": "source", "reload": "hot", "label": "网易账号歌单"},
}

_PROVIDER_KEYS = set(PROVIDERS.values())


# ------------------------------------------------------------------ .env 读写 --

def read_env() -> dict[str, str]:
    kv, _ = parse_env_file(ENV_PATH)
    return dict(kv)


def current_provider(values: dict[str, str]) -> str:
    for name, key in PROVIDERS.items():
        if values.get(key, "false").lower() in ("true", "1", "yes"):
            return name
    return ""


def write_env(updates: dict[str, str]) -> list[str]:
    """把 updates 合并进 .env（显式覆盖），原子写 + 备份 + 保留用户自定义键与注释。

    返回实际发生变化的键列表。
    """
    existing_kv, others = parse_env_file(ENV_PATH)
    existing_map = dict(existing_kv)
    changed: list[str] = []
    for key, value in updates.items():
        if existing_map.get(key) != value:
            changed.append(key)
    if not changed:
        return []
    if ENV_PATH.exists():
        # with_suffix 会把 ".env" 当后缀替换，产出 ".env.env.webui.bak" 畸形名；拼名字才是 /repo/.env.webui.bak
        backup = ENV_PATH.with_name(ENV_PATH.name + ".webui.bak")
        try:
            backup.write_bytes(ENV_PATH.read_bytes())
            os.chmod(backup, 0o600)  # write_bytes 按 umask 落盘（0644），密钥备份必须收紧
        except OSError as exc:  # 备份失败不阻断写入，但要有迹可循
            logger.warning("webui env backup failed: %s", exc)
    merged = [(k, updates.get(k, v)) if k in updates else (k, v) for k, v in existing_kv]
    seen = {k for k, _ in merged}
    merged.extend((k, v) for k, v in updates.items() if k not in seen)
    write_env_atomic(
        ENV_PATH,
        render_env(
            merged,
            CONF["env_header"],
            trailing=preserve_user_comments(others, header=CONF["env_header"]),
        ),
    )
    return changed


# ------------------------------------------------------------------ supervisor --

def supervisorctl(*args: str, timeout: float = 20.0) -> tuple[int, str]:
    # WEBUI_SUPERVISORCTL 可携带参数（如 "supervisorctl -c /path/supervisord.conf"），
    # 按 shell 词法拆分；默认裸 "supervisorctl" 拆分后行为不变。
    cmd = shlex.split(CONF["supervisorctl"]) + list(args)
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    except FileNotFoundError:
        return 127, "supervisorctl not found"
    except subprocess.TimeoutExpired:
        return 124, f"supervisorctl {' '.join(args)} timed out"
    output = (proc.stdout or "") + (proc.stderr or "")
    return proc.returncode, output.strip()


def supervisor_status() -> dict[str, dict]:
    # supervisorctl status 的退出码语义是“是否全部 RUNNING”（存在 STOPPED 即 3、
    # 存在 FATAL 即 4），按需加载架构下未选中的音源常驻 STOPPED 是正常态，
    # 不能用退出码判成败：只认输出里能解析出的状态行；连接失败等异常输出
    # 解析不出任何状态行，自然返回空表（前端显示未知）。
    _, out = supervisorctl("status")
    result: dict[str, dict] = {}
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[1] in ("RUNNING", "STOPPED", "STARTING", "FATAL", "BACKOFF", "EXITED"):
            result[parts[0]] = {"state": parts[1], "detail": " ".join(parts[2:])}
    return result


PROVIDER_PROGRAMS = {
    "musicdl": ["musicdl"],
    "musicbox": ["musicbox"],
    "lxmusic": ["lxserver", "lxmusic"],
}
PROVIDER_PROGRAM = {"musicdl": "musicdl", "musicbox": "musicbox", "lxmusic": "lxmusic"}  # 兼容单名引用
PROVIDER_HEALTH = {"musicdl": CONF["musicdl_url"], "musicbox": CONF["musicbox_url"], "lxmusic": CONF["lx_url"]}


def switch_provider_process(old: str, new: str) -> list[dict]:
    """切源进程：先停旧再起新；失败逐项记录，不抛出。"""
    actions: list[dict] = []
    if old and old != new:
        # 停旧：按逆序停止（例如先停 lxmusic 再停 lxserver）
        old_progs = reversed(PROVIDER_PROGRAMS.get(old, [old]))
        for prog in old_progs:
            code, out = supervisorctl("stop", prog)
            actions.append({"kind": "process", "program": prog, "op": "stop",
                            "ok": code == 0, "error": "" if code == 0 else out})
    if new:
        # 起新：按顺序启动（例如先起 lxserver 再起 lxmusic）
        new_progs = PROVIDER_PROGRAMS.get(new, [new])
        for prog in new_progs:
            code, out = supervisorctl("start", prog)
            actions.append({"kind": "process", "program": prog, "op": "start",
                            "ok": code == 0, "error": "" if code == 0 else out})
    return actions


# ------------------------------------------------------------------ 音源预览（临时拉起） --
# WebUI 点选未启用的音源卡片时临时拉起对应进程（仅 supervisorctl，不写 .env），
# 让 lx 测试 / musicdl 平台列表 / 网易扫码立即可用：
# - 保存后转正（正式启用）或被立即清退（api_config 保存路径 reconcile）；
# - 只点选未保存的，PREVIEW_TTL 秒无访问后自动停止（选平台/测试源/扫码会续期）。
PREVIEW_TTL = 300.0
_preview_until: dict[str, float] = {}


def preview_seconds_left(provider: str) -> float:
    deadline = _preview_until.get(provider)
    return max(0.0, deadline - time.monotonic()) if deadline else 0.0


def preview_renew(provider: str) -> None:
    if provider in _preview_until:
        _preview_until[provider] = time.monotonic() + PREVIEW_TTL


def preview_reap() -> list[str]:
    """清退到期预览：已随保存启用的转正（移出预览表，进程常驻），其余停止。

    stop 失败（supervisorctl 抖动/超时）不 pop 表项：deadline 仍过期，
    下一轮 reaper 会重试——否则预览进程漏停后常驻，无人再管。
    """
    stopped: list[str] = []
    enabled = current_provider(read_env())
    for provider, deadline in list(_preview_until.items()):
        if provider == enabled:
            _preview_until.pop(provider, None)
        elif deadline <= time.monotonic():
            all_ok = True
            for prog in reversed(PROVIDER_PROGRAMS.get(provider, [provider])):
                code, out = supervisorctl("stop", prog)
                if code != 0:
                    all_ok = False
                    logger.warning("预览到期但停止失败（下轮重试）%s(%s): %s", provider, prog, out)
            if all_ok:
                _preview_until.pop(provider, None)
                logger.info("预览到期，停止音源进程 %s", provider)
                stopped.append(provider)
    return stopped


def preview_reconcile_after_save() -> list[dict]:
    """保存成功后的收尾：预览转正的进程保留，其余预览进程立即停止。"""
    enabled = current_provider(read_env())
    actions: list[dict] = []
    for provider in list(_preview_until):
        if provider == enabled:
            _preview_until.pop(provider, None)
            continue
        _preview_until.pop(provider, None)
        for prog in reversed(PROVIDER_PROGRAMS.get(provider, [provider])):
            code, out = supervisorctl("stop", prog)
            actions.append({"kind": "process", "program": prog, "op": "stop",
                            "ok": code == 0, "error": "" if code == 0 else out, "preview": True})
    return actions


# ------------------------------------------------------------------ 校验 --

def _normalize_lx_source_list(raw) -> str:
    if isinstance(raw, str):
        text = raw.strip()
        if not text:
            return "[]"
        try:
            items = json.loads(text)
        except Exception as exc:
            raise ValueError(f"LX_SOURCE_LIST: 不是合法的 JSON 数组: {exc}") from exc
    elif isinstance(raw, list):
        items = raw
    else:
        raise ValueError(f"LX_SOURCE_LIST: 期望 JSON 数组，收到 {type(raw).__name__}")

    if not isinstance(items, list):
        raise ValueError("LX_SOURCE_LIST: 期望 JSON 数组，收到 JSON 对象或其他类型")

    normalized: list[dict[str, str]] = []
    seen_urls: set[str] = set()
    for item in items[:50]:  # 上限 50 条
        if not isinstance(item, dict):
            continue
        url = str(item.get("url") or "").strip()
        if not url:
            continue
        url_lower = url.lower()
        if not (url_lower.startswith("http://") or url_lower.startswith("https://") or url_lower.startswith("file://")):
            continue
        if len(url) > 2000:
            continue
        if url in seen_urls:
            continue
        seen_urls.add(url)

        name = str(item.get("name") or "").strip()
        name = re.sub(r"[\r\n\t]+", " ", name).strip()[:80]
        normalized.append({"name": name, "url": url, "active": bool(item.get("active"))})

    return json.dumps(normalized, ensure_ascii=False, separators=(",", ":"))


def _lx_list_items(raw) -> list[dict]:
    """解析 LX_SOURCE_LIST JSON 字符串为 dict 列表（非法输入返回空列表）。"""
    if isinstance(raw, list):
        items = raw
    else:
        try:
            items = json.loads(str(raw or "").strip() or "[]")
        except Exception:
            return []
    if not isinstance(items, list):
        return []
    return [i for i in items if isinstance(i, dict)]


def _list_active_urls(values: dict) -> set[str]:
    """从 .env 值推导激活 URL 集合：优先列表 active 标记；无标记回退 LX_SOURCE_URL 单值（旧数据）。"""
    urls: set[str] = set()
    for item in _lx_list_items(values.get("LX_SOURCE_LIST")):
        if item.get("active"):
            url = str(item.get("url") or "").strip()
            if url:
                urls.add(url)
    if not urls:
        url = str(values.get("LX_SOURCE_URL") or "").strip()
        if url:
            urls.add(url)
    return urls


def _derive_lx_list_actives(items: list[dict], ref_url: str) -> list[dict]:
    """兼容升级：列表无任何 active 标记时按 LX_SOURCE_URL 推导（全部项显式落布尔）。"""
    if items and not any(i.get("active") for i in items):
        for item in items:
            item["active"] = bool(ref_url) and str(item.get("url") or "").strip() == ref_url
    return items


def _dumps_lx_list(items: list[dict]) -> str:
    return json.dumps(items, ensure_ascii=False, separators=(",", ":"))


async def _lx_enabled_platforms(request: Request) -> list[str]:
    """读取 lxmusic 当前全部启用源的声明平台并集（保持出现顺序）；不可达返回空列表。"""
    try:
        resp = await get_http(request).get(f"{CONF['lx_url']}/api/v1/source", timeout=10.0)
        data = _resp_json(resp)
        sources = ((data or {}).get("data") or {}).get("sources") or []
        platforms: list[str] = []
        for s in sources:
            for p in (s or {}).get("platforms") or []:
                p = str(p).strip()
                if p and p not in platforms:
                    platforms.append(p)
        return platforms
    except Exception:  # noqa: BLE001
        return []


def _normalize_dir_path(label: str, raw) -> str:
    """储存目录归一化：空值合法（=恢复默认/自动探测）；要求绝对路径、
    拒绝 .. 段与换行/空字符；折叠多余斜杠与尾斜杠。"""
    text = str(raw or "").strip()
    if not text:
        return ""
    if any(ch in text for ch in "\r\n\x00"):
        raise ValueError(f"{label}: 路径不能包含换行或空字符")
    if not text.startswith("/"):
        raise ValueError(f"{label}: 必须是以 / 开头的绝对路径，收到 {raw!r}")
    segs = [seg for seg in text.split("/") if seg]
    if not segs:
        raise ValueError(f"{label}: 不能是根目录 /")
    if ".." in segs:
        raise ValueError(f"{label}: 路径不能包含 .. 段")
    return "/" + "/".join(segs)


def _is_dir_within(child: str, parent: str) -> bool:
    """child 是否与 parent 相同或位于 parent 之下（均应为归一化后的绝对路径）。"""
    return child == parent or child.startswith(parent.rstrip("/") + "/")


def _normalize_value(key: str, raw) -> str:
    if key == "LX_SOURCE_LIST":
        return _normalize_lx_source_list(raw)
    spec = SCHEMA[key]
    kind = spec["kind"]
    if kind == "dir":
        return _normalize_dir_path(spec.get("label", key), raw)
    if kind == "bool":
        if isinstance(raw, bool):
            return "true" if raw else "false"
        text = str(raw).strip().lower()
        if text in ("true", "1", "yes", "on"):
            return "true"
        if text in ("false", "0", "no", "off", ""):
            return "false"
        raise ValueError(f"{key}: 期望 true/false，收到 {raw!r}")
    if kind == "int":
        try:
            num = int(str(raw).strip())
        except ValueError as exc:
            raise ValueError(f"{key}: 期望整数，收到 {raw!r}") from exc
        num = max(int(spec.get("min", num)), min(int(spec.get("max", num)), num))
        return str(num)
    if kind == "enum":
        text = str(raw).strip()
        if text not in spec["values"]:
            raise ValueError(f"{key}: 可选值 {'/'.join(spec['values'])}，收到 {raw!r}")
        return text
    if kind == "csv":
        items: list[str] = []
        if isinstance(raw, list):
            raw_list = [str(x) for x in raw]
        else:
            raw_list = [x for x in str(raw).replace("，", ",").split(",")]
        for item in raw_list:
            item = item.strip()
            if item and item not in items:
                items.append(item)
        return ",".join(items)
    return str(raw).strip()


def validate_updates(values: dict) -> dict[str, str]:
    updates: dict[str, str] = {}
    for key, raw in (values or {}).items():
        if key not in SCHEMA:
            raise ValueError(f"不支持的配置键: {key}")
        updates[key] = _normalize_value(key, raw)
    # 三选一互斥：以"应用后的最终状态"判断
    final = dict(read_env())
    final.update(updates)
    # 储存目录互斥：缓存目录与下载目录不能相同或互为父子（否则滚动缓存被官方扫描进曲库）
    final_cache = (final.get("FNMUSIC_CACHE_DIR") or "").strip()
    final_dl = (final.get("FNMUSIC_TEE_SAVE_DIR") or "").strip()
    if final_cache and final_dl and (_is_dir_within(final_cache, final_dl) or _is_dir_within(final_dl, final_cache)):
        raise ValueError("歌曲缓存目录与下载目录不能相同或互为父子目录")
    enabled = [name for name, key in PROVIDERS.items()
               if final.get(key, SCHEMA[key]["default"]).lower() in ("true", "1", "yes")]
    if len(enabled) > 1:
        raise ValueError(f"音源三选一：{'、'.join(enabled)} 同时启用，请只保留一个")
    if updates.keys() & _PROVIDER_KEYS and not enabled:
        raise ValueError("至少需要启用一个音源")
    return updates


# ------------------------------------------------------------------ HTTP 客户端 --

from contextlib import asynccontextmanager


@asynccontextmanager
async def _lifespan(_app: FastAPI):
    async def _preview_reaper():
        while True:
            await asyncio.sleep(15.0)
            try:
                preview_reap()
            except Exception:  # noqa: BLE001
                logger.exception("预览清退循环异常")
    reaper = asyncio.create_task(_preview_reaper())
    try:
        yield
    finally:
        reaper.cancel()
        client = getattr(_app.state, "http", None)
        if client is not None:
            await client.aclose()
            _app.state.http = None


app = FastAPI(title="fnmusic-webui", version=SERVICE_VERSION, lifespan=_lifespan)


def get_http(request: Request) -> httpx.AsyncClient:
    client = getattr(request.app.state, "http", None)
    if client is None:
        client = httpx.AsyncClient(timeout=httpx.Timeout(8.0, connect=3.0))
        request.app.state.http = client
    return client


def _resp_json(resp: httpx.Response) -> dict:
    """防御性解析同容器服务的响应体：上游裸 500 等非 JSON 文本时返回带 error 的
    字典而不是抛 JSONDecodeError（否则自身也会 500，用户只能看到 "HTTP 500"）。"""
    try:
        return resp.json() if resp.content else {}
    except Exception:  # noqa: BLE001
        return {"ok": False, "error": f"上游返回非 JSON 响应（HTTP {resp.status_code}）"}


async def _fetch_json(request: Request, url: str, *, timeout: float = 4.0) -> "tuple[bool, dict]":
    client = get_http(request)
    try:
        resp = await client.get(url, timeout=timeout)
        data = _resp_json(resp)
        return resp.status_code < 400 and data.get("ok", True), data
    except Exception as exc:  # noqa: BLE001
        return False, {"error": str(exc)}


def _read_version() -> str:
    try:
        return VERSION_PATH.read_text(encoding="utf-8").strip()
    except OSError:
        return SERVICE_VERSION


# ------------------------------------------------------------------ API --

@app.get("/healthz")
async def healthz():
    return {"ok": True}


def _header_map(scope) -> dict[str, str]:
    out: dict[str, str] = {}
    for key, value in scope.get("headers") or []:
        out[key.decode("latin-1").lower()] = value.decode("latin-1")
    return out


def _is_admin(headers: dict[str, str]) -> bool:
    return headers.get("x-trim-isadmin", "").lower() == "true"


@app.get("/api/status")
async def api_status(request: Request):
    values = read_env()
    provider = current_provider(values)
    processes = supervisor_status()
    services: dict[str, dict] = {}
    for name, base in (("musicdl", CONF["musicdl_url"]), ("musicbox", CONF["musicbox_url"]),
                       ("lxmusic", CONF["lx_url"])):
        if name in PROVIDERS and name != provider:
            services[name] = {"reachable": False, "note": "未启用（按需未启动）"}
            continue
        ok, data = await _fetch_json(request, f"{base}/healthz")
        services[name] = {"reachable": ok, "detail": data if ok else data.get("error", "")}
    lx_source = None
    if provider == "lxmusic":
        ok, data = await _fetch_json(request, f"{CONF['lx_url']}/api/v1/source")
        lx_source = data.get("data") if ok else {"error": data.get("error", "unreachable")}
    return {
        "ok": True,
        "version": _read_version(),
        "deploy_mode": values.get("FNMUSIC_DEPLOY_MODE", "docker"),
        "current_provider": provider or "none",
        "processes": {name: processes.get(name, {"state": "UNKNOWN", "detail": ""})
                      for name in ("musicdl", "musicbox", "lxmusic", "webui")},
        "previews": {p: round(preview_seconds_left(p)) for p in list(_preview_until)},
        "services": services,
        "lx_source": lx_source,
    }


@app.get("/api/config")
async def api_config():
    values = read_env()
    # 兼容升级：列表项缺 active 标记时按 LX_SOURCE_URL 推导（旧数据一次加载即升级）
    ref_url = str(values.get("LX_SOURCE_URL") or "").strip()
    if ref_url:
        items = _derive_lx_list_actives(_lx_list_items(values.get("LX_SOURCE_LIST")), ref_url)
        if items:
            values["LX_SOURCE_LIST"] = _dumps_lx_list(items)
    return {
        "ok": True,
        "values": {key: values.get(key, spec["default"]) for key, spec in SCHEMA.items()},
        "schema": SCHEMA,
        "env_path": str(ENV_PATH),
    }


class ConfigBody(BaseModel):
    values: dict


class PreviewBody(BaseModel):
    provider: str


@app.post("/api/preview")
async def api_preview(body: PreviewBody, request: Request):
    """点选未启用的音源卡片：临时拉起进程供预览（不写 .env，倒计时自动停止）。"""
    provider = body.provider
    if provider not in PROVIDERS:
        raise HTTPException(status_code=400, detail="provider 必须是 musicdl/musicbox/lxmusic 之一")
    if current_provider(read_env()) == provider:
        return {"ok": True, "preview": False, "note": "该音源已启用，进程常驻"}
    if preview_seconds_left(provider) > 0:
        preview_renew(provider)
        return {"ok": True, "preview": True, "seconds_left": preview_seconds_left(provider)}
    started: list[str] = []
    for prog in PROVIDER_PROGRAMS.get(provider, [provider]):
        code, out = supervisorctl("start", prog)
        if code != 0:
            for p in reversed(started):
                supervisorctl("stop", p)
            return JSONResponse(content={"ok": False, "error": f"supervisorctl start {prog} 失败: {out}"}, status_code=500)
        started.append(prog)
    client = get_http(request)
    healthy = False
    for _ in range(60):  # 等待服务真正可用（healthz），最长约 30s
        try:
            r = await client.get(f"{PROVIDER_HEALTH[provider]}/healthz", timeout=2.0)
            if r.status_code == 200:
                healthy = True
                break
        except httpx.HTTPError:
            pass
        await asyncio.sleep(0.5)
    if not healthy:
        for p in reversed(started):
            supervisorctl("stop", p)
        return JSONResponse(content={"ok": False, "error": f"{provider} 启动后未能通过健康检查"}, status_code=504)
    _preview_until[provider] = time.monotonic() + PREVIEW_TTL
    return {"ok": True, "preview": True, "seconds_left": PREVIEW_TTL}


@app.put("/api/config")
async def api_config_put(body: ConfigBody, request: Request):
    before = read_env()
    try:
        updates = validate_updates(body.values)
    except ValueError as exc:
        return JSONResponse(content={"ok": False, "error": str(exc)}, status_code=400)

    after_preview = dict(before)
    after_preview.update(updates)
    lx_provider = current_provider(after_preview) == "lxmusic"

    # lx 多源激活集合：active_items 待激活列表、to_activate 新激活（需校验）、to_deactivate 被取消激活
    active_items: list[dict] = []
    to_activate: list[dict] = []
    to_deactivate: list[dict] = []
    lx_reconcile = False
    if lx_provider and "LX_SOURCE_LIST" in updates:
        items = _derive_lx_list_actives(
            _lx_list_items(updates["LX_SOURCE_LIST"]),
            str(updates.get("LX_SOURCE_URL") or after_preview.get("LX_SOURCE_URL") or "").strip(),
        )
        active_items = [i for i in items if i.get("active") and str(i.get("url") or "").strip()]
        if not active_items:
            return JSONResponse(
                content={"ok": False, "error": "请至少激活一个洛雪源"}, status_code=400
            )
        if active_items:
            lx_reconcile = True
            # LX_SOURCE_URL 退化为派生兼容字段 = 第一个激活项
            updates["LX_SOURCE_URL"] = str(active_items[0]["url"]).strip()
            after_preview["LX_SOURCE_URL"] = updates["LX_SOURCE_URL"]
            before_active = _list_active_urls(before)
            to_activate = [i for i in active_items
                           if str(i["url"]).strip() not in before_active]
            before_items = {str(i.get("url") or "").strip(): i for i in _lx_list_items(before.get("LX_SOURCE_LIST"))}
            new_active = {str(i["url"]).strip() for i in active_items}
            to_deactivate = [before_items.get(url, {"url": url})
                             for url in before_active if url not in new_active]
            updates["LX_SOURCE_LIST"] = _dumps_lx_list(items)

    # lx 换源前置校验：新激活的源必须先通过 lxmusic verify 才写入
    lx_url_changed = updates.get("LX_SOURCE_URL") not in (None, before.get("LX_SOURCE_URL", ""))
    verify_urls: list[str] = []
    if lx_provider:
        if lx_reconcile:
            verify_urls = [str(i["url"]).strip() for i in to_activate]
        elif lx_url_changed:
            verify_urls = [str(updates["LX_SOURCE_URL"] or "").strip()]
    client = get_http(request)
    union_acc: list[str] = []  # LX_SOURCES 推导：新激活源声明平台 ∪ 现有启用源声明平台
    for url in verify_urls:
        if not url:
            continue
        try:
            resp = await client.post(f"{CONF['lx_url']}/api/v1/source/verify",
                                     json={"url": url}, timeout=130.0)
            report = _resp_json(resp)
        except Exception as exc:  # noqa: BLE001
            report = {"ok": False, "data": {"message": str(exc)}}
        if not report.get("ok"):
            message = (report.get("data") or {}).get("message") or report.get("error") or "校验失败"
            return JSONResponse(
                content={"ok": False, "error": f"洛雪源校验未通过：{message}"}, status_code=400
            )
        # LX_SOURCES 推导累计各新激活源声明平台
        for p in (report.get("data") or {}).get("platforms") or []:
            p = str(p).strip()
            if p and p not in union_acc:
                union_acc.append(p)

    if lx_reconcile:
        # 并入现有启用源声明平台（激活前读取，保持出现顺序）
        for p in await _lx_enabled_platforms(request):
            p = str(p).strip()
            if p and p not in union_acc:
                union_acc.append(p)
    if union_acc:
        updates.setdefault("LX_SOURCES", ",".join(union_acc))

    old_provider = current_provider(before)
    changed = write_env(updates)
    after = read_env()
    new_provider = current_provider(after)
    actions: list[dict] = []

    # 即使 .env 内容无 diff，若显式提交了 LX_SOURCE_URL/LX_SOURCE_LIST 且当前是 lxmusic，仍应重试激活
    force_lx_activate = (
        new_provider == "lxmusic"
        and ("LX_SOURCE_URL" in updates or "LX_SOURCE_LIST" in updates)
        and bool(after.get("LX_SOURCE_URL") or after.get("LX_SOURCE_LIST"))
    )

    if not changed and not force_lx_activate and not _preview_until:
        return {"ok": True, "changed": [], "actions": [], "note": "配置无变化"}

    # 音源切换（先停旧再起新）
    if old_provider != new_provider:
        actions.extend(switch_provider_process(old_provider, new_provider))

    async def _lx_source_post(payload: dict, source: str, op: str) -> None:
        try:
            resp = await client.post(f"{CONF['lx_url']}/api/v1/source",
                                     json=payload, timeout=130.0)
            api_payload = _resp_json(resp)
            ok = resp.status_code == 200 and api_payload.get("ok", False)
            err = "" if ok else (api_payload.get("error") or f"HTTP {resp.status_code}")
        except Exception as exc:  # noqa: BLE001
            ok, err = False, str(exc)
        actions.append({"kind": "lx_activate", "op": op, "source": source,
                        "ok": ok, "error": err or ""})

    # lx 多源对账激活：停用被取消项，再按列表顺序叠加激活全部 active 项
    if new_provider == "lxmusic" and (lx_reconcile or lx_url_changed or force_lx_activate):
        if lx_reconcile:
            for item in to_deactivate:
                url = str(item.get("url") or "").strip()
                await _lx_source_post({"url": url, "enabled": False},
                                      str(item.get("name") or "") or url, "deactivate")
            for item in active_items:
                url = str(item["url"]).strip()
                await _lx_source_post({"url": url},
                                      str(item.get("name") or "") or url, "activate")
        else:
            await _lx_source_post({"url": after["LX_SOURCE_URL"]}, "", "activate")
    elif new_provider == "musicdl" and (
        "FNMUSIC_ONLINE_SOURCES" in changed or "MUSICDL_SOURCES" in changed
    ):
        code, out = supervisorctl("restart", "musicdl")
        actions.append({"kind": "process", "program": "musicdl", "op": "restart",
                        "ok": code == 0, "error": "" if code == 0 else out})

    # 预览收尾：保存启用的转正常驻，其余预览进程立即停止
    actions.extend(preview_reconcile_after_save())

    restart_keys = [k for k in changed if SCHEMA.get(k, {}).get("reload") == "restart"]
    return {"ok": True, "changed": changed, "actions": actions, "restart_keys": restart_keys}


@app.post("/api/lx/verify")
async def api_lx_verify(body: ConfigBody, request: Request):
    preview_renew("lxmusic")  # 预览期间测试源视为活跃，续期倒计时
    url = str((body.values or {}).get("url") or "").strip()
    if not url.lower().startswith(("http://", "https://", "file://")):
        raise HTTPException(status_code=400, detail="url 必须以 http:// 、https:// 或 file:// 开头")
    client = get_http(request)
    try:
        resp = await client.post(f"{CONF['lx_url']}/api/v1/source/verify",
                                 json={"url": url}, timeout=130.0)
        return JSONResponse(content=_resp_json(resp) or {"ok": False},
                            status_code=resp.status_code)
    except httpx.HTTPError as exc:
        raise HTTPException(status_code=502, detail=f"lxmusic 服务不可达: {exc}") from exc


def _lx_script_limits(filename: str, script: str) -> None:
    if not (filename or "").strip().lower().endswith(".js"):
        raise HTTPException(status_code=400, detail="只支持 .js 后缀的洛雪源脚本文件")
    if len(script.encode("utf-8")) > 9_000_000:
        raise HTTPException(status_code=400, detail="脚本超过 9MB 大小上限")


@app.post("/api/lx/upload")
async def api_lx_upload(request: Request):
    """上传 .js：管理页/NAS 选择发 JSON {filename, script}，也接受 multipart 文件。

    校验后转给 lxmusic 落盘，返回 file:// URL。
    """
    preview_renew("lxmusic")
    content_type = (request.headers.get("content-type") or "").lower()
    if "application/json" in content_type:
        try:
            payload = await request.json()
        except Exception as exc:  # noqa: BLE001
            raise HTTPException(status_code=400, detail="请求体必须是 JSON") from exc
        if not isinstance(payload, dict):
            raise HTTPException(status_code=400, detail="请求体必须是 JSON 对象")
        filename = str(payload.get("filename") or "")
        script = payload.get("script")
        if not isinstance(script, str) or not script:
            raise HTTPException(status_code=400, detail="缺少 script")
    elif "multipart/form-data" in content_type:
        form = await request.form()
        upload = form.get("file")
        if upload is None or not hasattr(upload, "filename"):
            raise HTTPException(status_code=400, detail="缺少 file 字段")
        filename = upload.filename or ""
        raw = await upload.read()
        if len(raw) > 9_000_000:
            raise HTTPException(status_code=400, detail="脚本超过 9MB 大小上限")
        try:
            script = raw.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise HTTPException(status_code=400, detail="脚本不是有效的 UTF-8 文本") from exc
    else:
        raise HTTPException(
            status_code=400, detail="请用 application/json 或 multipart/form-data 上传文件")
    _lx_script_limits(filename, script)
    client = get_http(request)
    try:
        resp = await client.post(f"{CONF['lx_url']}/api/v1/source/upload",
                                 json={"filename": filename, "script": script},
                                 timeout=30.0)
        return JSONResponse(content=_resp_json(resp) or {"ok": False},
                            status_code=resp.status_code)
    except httpx.HTTPError as exc:
        raise HTTPException(status_code=502, detail=f"lxmusic 服务不可达: {exc}") from exc


@app.get("/api/platforms")
async def api_platforms(request: Request):
    preview_renew("musicdl")  # 预览期间查看平台列表视为活跃，续期倒计时
    ok, data = await _fetch_json(request, f"{CONF['musicdl_url']}/sources")
    if not ok:
        return JSONResponse(
            content={"ok": False, "error": data.get("error", "musicdl 服务不可达"),
                     "hint": "musicdl 进程未启用时无法获取平台列表"},
            status_code=503,
        )
    return {"ok": True, "enabled": data.get("enabled") or [], "registered": data.get("registered") or []}


# ------------------------------------------------- 网易扫码（反代 musicbox） --

@app.api_route("/api/netease/auth/{path:path}", methods=["GET", "POST"])
async def netease_auth_proxy(path: str, request: Request):
    """透传 musicbox 的 auth 接口（登录/轮询/状态），路径段白名单内。"""
    if path not in ("login", "login/check", "status"):
        raise HTTPException(status_code=404, detail="unknown auth endpoint")
    preview_renew("musicbox")  # 预览期间扫码/查状态视为活跃，续期倒计时
    target = f"{CONF['musicbox_url']}/api/v1/auth/{path}"
    client = get_http(request)
    try:
        resp = await client.request(
            request.method, target,
            params=dict(request.query_params),
            json=(await request.json()) if request.method == "POST" and await request.body() else None,
            timeout=30.0,
        )
    except httpx.HTTPError as exc:
        raise HTTPException(status_code=502, detail=f"musicbox 服务不可达: {exc}") from exc
    return Response(content=resp.content, status_code=resp.status_code,
                    media_type=resp.headers.get("content-type", "application/json"))


@app.get("/api/netease/qr")
async def netease_qr(unikey: str = Query(...)):
    """把登录链接渲染为 SVG 二维码（无 PIL 依赖，前端直接 <img> 展示）。"""
    if not unikey.strip():
        raise HTTPException(status_code=400, detail="unikey cannot be empty")
    try:
        import qrcode
        import qrcode.image.svg
    except ImportError as exc:
        raise HTTPException(status_code=501, detail="qrcode not installed") from exc
    url = f"https://music.163.com/login?codekey={unikey.strip()}"
    img = qrcode.make(url, image_factory=qrcode.image.svg.SvgPathImage, box_size=12)
    buf = io.BytesIO()
    img.save(buf)
    return Response(content=buf.getvalue(), media_type="image/svg+xml")


@app.post("/api/fs-check")
async def api_fs_check():
    """目录权限校验占位端点（直连 8774 场景）。

    桌面链路（统一网关）中该路径由宿主机侧 webui_gateway（root）拦截应答，
    不会到达这里；能到达说明是独立浏览器/直连端口环境，WebUI 容器内看不到
    宿主机真实目录，无法给出可信的可写性结论，明确回 501 让前端降级放行。
    """
    raise HTTPException(status_code=501, detail="直连模式不支持目录权限校验，请在飞牛桌面内打开管理台")


# ------------------------------------------------------------------ 静态前端 --

@app.get("/")
async def index():
    return FileResponse(STATIC_DIR / "index.html")


app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")

# 飞牛桌面 iframe 不能嵌 http://主机:8774（桌面是 HTTPS，混合内容会被浏览器丢掉，窗口一片空白）。
# 入口改走网关同源路径 /app/fnmusic-ext，这里把该前缀剥掉，直连 :8774 的 /api 不受影响。
DESKTOP_PREFIX = "/app/fnmusic-ext"


class DesktopPrefixMiddleware:
    def __init__(self, app, prefix: str = DESKTOP_PREFIX):
        self.app = app
        self.prefix = prefix

    async def __call__(self, scope, receive, send):
        if scope["type"] in ("http", "websocket"):
            path = scope.get("path") or ""
            if path == self.prefix or path.startswith(self.prefix + "/"):
                scope = dict(scope)
                stripped = path[len(self.prefix):] or "/"
                scope["path"] = stripped
                if isinstance(scope.get("raw_path"), (bytes, bytearray)):
                    scope["raw_path"] = stripped.encode("ascii")
        await self.app(scope, receive, send)


class AuthMiddleware:
    """管理接口要求飞牛网关注入的管理员身份。桌面前缀由外层中间件先剥掉。"""

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return
        path = scope.get("path") or ""
        if not path.startswith("/api/") or _is_admin(_header_map(scope)):
            await self.app(scope, receive, send)
            return
        body = '{"ok":false,"error":"需要管理员"}'.encode()
        await send({
            "type": "http.response.start",
            "status": 403,
            "headers": [
                [b"content-type", b"application/json; charset=utf-8"],
                [b"content-length", str(len(body)).encode()],
            ],
        })
        await send({"type": "http.response.body", "body": body})


app.add_middleware(AuthMiddleware)
app.add_middleware(DesktopPrefixMiddleware)
